
##docker-compose.yml
version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_root_pass
      MYSQL_DATABASE: my_database
    ports:
      - "3307:3306"
